# OSX and Windows work, just commented to save Travis resources
language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true
  
python: 3.6

env: FC=gfortran

addons:
  apt:
#    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran
#    - octave  # needs Octave >= 4.2 for textscan to work properly
# https://www.gnu.org/software/octave/NEWS-4.2.html
#    - libnetcdf-dev
#    - libnetcdff-dev
#    - libopenmpi-dev
#    - openmpi-bin

matrix:
  include:
  - os: linux
#  - os: osx
#    before_install:
#    - brew update > /dev/null
#    - brew install gcc > /dev/null
#  - os: windows
#    install:
#    - pip install -e .

install: pip install -e .

script: pytest -v
